name: Docker Image CI

on:
  push:
    branches: [ "feat/filemanager" ]
  pull_request:
    branches: [ "feat/filemanager" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag akas-ia/filemanager-secu:$(date +%s)
    - name: Push the Docker image
      run: docker push akas-ia/filemanager-secu:latest
